### ISSUE TITLE
Version 0.5.2 crashes when trying to exclude a path

### ISSUE THREAD

**Issue by Wasnix** [UnevenSoftware/LeafPic#293] opened 2016-08-18 09:31 UTC
LeafPic crashes when I try to exclude a path with some images. logcat shows that there is something wrong with a SQL database:

---

I/ActivityManager( 8958): Start proc org.horaapps.leafpic for activity org.horaapps.leafpic/.Activities.SplashScreen: pid=15078 uid=10127 gids={50127, 1028, 1015, 1023, 3003}
E/AndroidRuntime(15078): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(15078): Process: org.horaapps.leafpic, PID: 15078
E/AndroidRuntime(15078): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(15078):        at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(15078):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(15078):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(15078):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(15078):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(15078):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(15078):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(15078):        at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(15078): Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (Sqlite code 14): Could not open database, (OS error - 2:No such file or directory)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:235)
E/AndroidRuntime(15078):        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
E/AndroidRuntime(15078):        at org.horaapps.leafpic.Data.CustomAlbumsHandler.getExcludedFoldersPaths(CustomAlbumsHandler.java:109)
E/AndroidRuntime(15078):        at org.horaapps.leafpic.Data.Providers.MediaStoreProvider.getAlbums(MediaStoreProvider.java:85)
E/AndroidRuntime(15078):        at org.horaapps.leafpic.Data.Providers.MediaStoreProvider.getAlbums(MediaStoreProvider.java:35)
E/AndroidRuntime(15078):        at org.horaapps.leafpic.Data.HandlingAlbums.loadAlbums(HandlingAlbums.java:70)
E/AndroidRuntime(15078):        at org.horaapps.leafpic.Activities.SplashScreen$PrefetchAlbumsData.doInBackground(SplashScreen.java:152)
E/AndroidRuntime(15078):        at org.horaapps.leafpic.Activities.SplashScreen$PrefetchAlbumsData.doInBackground(SplashScreen.java:143)
E/AndroidRuntime(15078):        at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(15078):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(15078):        ... 4 more
I/ActivityManager( 8958): Process org.horaapps.leafpic (pid 15078) has died.

---

**Comment by Valeria-AT** [comment] 2016-08-19 06:12
Second duplicate of https://github.com/HoraApps/LeafPic/issues/272 ?

**Comment by dnldsht** [comment] 2016-08-19 13:25
I'm gonna close this since it is a duplicate and it is fixed in the dev branch

**Closed as completed by dnldsht** 2016-08-19 13:25 UTC
