### ISSUE TITLE
Some icons are cut

### ISSUE THREAD

**Issue by mwolos** [UnevenSoftware/LeafPic#303] opened 2016-08-24 23:58 UTC
Hi, I'm running Android Nougat on a Nexus 6P.

The problem I'm seeing is some icons are showing up cut on two sides. The icons affected are the selection tick and the video icon. Tapping over the icon seems to fix it.

**Comment by dnldsht** [comment] 2016-08-28 15:10
hey @dwma when you launch the app are they always croped? there are any case that they aren't croped?

**Comment by mwolos** [comment] 2016-08-28 21:34
They are always cropped. In the video icon case, sometimes scrolling up and down until the icon is hidden fixes it.

**Comment by g1lg1l** [comment] 2016-08-29 07:54
Fixed on the next release!:)
Cheers

**Comment by brandonio21** [comment] 2016-08-29 18:33
Note that this issue is related (maybe a duplicate of) https://github.com/HoraApps/LeafPic/issues/205

**Comment by dnldsht** [comment] 2016-08-29 18:45
closed since duplicate of #205 and fixed in the develop

**Closed as completed by dnldsht** 2016-08-29 18:45 UTC
Labels: bug, in progress
