### ISSUE TITLE
[BUG] Exclude button crashes LeafPic each time.

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#284] opened 2016-08-14 04:14 UTC
The exclude button always makes the app crash and I'm unsure as to why.

**Comment by Valeria-AT** [comment] 2016-08-14 07:27
https://github.com/HoraApps/LeafPic/issues/272 ?

**Comment by ghost** [comment] 2016-08-14 07:56
@Theobald93 can confirm it does the same for me.

**Comment by dnldsht** [comment] 2016-08-19 13:26
duplicate of #272 and fixed in the dev branch!

**Closed as completed by dnldsht** 2016-08-19 13:26 UTC
