### ISSUE TITLE
Photo editing tools

### ISSUE THREAD

**Issue by Chic999** [UnevenSoftware/LeafPic#258] opened 2016-08-10 01:41 UTC
Brightness
Contrast
Saturation
Ambiance
Highlights
Shadows
Warmth
Photogrid - dual, trio and quad grid
Drawing tools

**Comment by wyatt8740** [comment] 2016-08-10 04:33
These go beyond the expected functionality of an image gallery, IMO, and just equal feature creep.

Maybe a companion app to LeafPic, but adding these would add a LOT of complexity.

**Comment by dnldsht** [comment] 2016-08-10 12:12
the only thing that i love to implement is drawing tools.

for an advanced photo editing you can use [Snapseed](https://play.google.com/store/apps/details?id=com.niksoftware.snapseed&hl=en)!

**Comment by bkp23** [comment] 2016-08-10 14:21
I agree with Wyatt8740. There are _lots_ of photo editing apps out there. One of the things I love about LeafPic is that it focuses on just image viewing. It does one thing and it does it well.

**Comment by wyatt8740** [comment] 2016-08-10 17:49
@bkp23 Would you happen to be a unix (or linux) user, too?
You just quoted the unix philosophy verbatim :)

**Comment by tp0** [comment] 2016-08-11 17:14
I agree with others, LeafPic should focus on the viewing pics part.

Only thing I'd like to see is cropping. (EDIT: Forgot it is already there :P)

**Comment by rugk** [comment] 2016-08-13 08:09
Cropping is already implemented.

And yes there may be many photo editing tools for a
Android out there, but few are open source.

**Comment by dnldsht** [comment] 2016-09-29 20:39
closed since duplicate of #177

**Closed as completed** 2016-09-29 20:39 UTC
