### ISSUE TITLE
UX: Image clicking zooms out

### ISSUE THREAD

**Issue by therealmarv** [UnevenSoftware/LeafPic#310] opened 2016-09-01 11:18 UTC
To reproduce:
1. Zoom in
2. Click on image -> Zooms out (you see the entire image)

This is (for me) not a behaviour I like on an image viewer. Sometimes I click/touch on accident on a zoomed in image and then I'm for a second lost (where am I?).
It should be at least an option to turn off or on.

**Comment by touzainanboku** [comment] 2016-09-01 13:16
It's actually not the tapping that causes the issue, it's going into fullscreen mode. It's reproducable even without tapping. Just open image, zoom in, wait a few seconds for it to go into fullscreen, and it zooms out. 

Also a duplicate of #264.

**Closed as completed** 2017-11-28 10:20 UTC
