### ISSUE TITLE
Pin Albums to Top

### ISSUE THREAD

**Issue by Ketrel** [UnevenSoftware/LeafPic#330] opened 2016-09-19 16:58 UTC
I'd like to be able to pin certain albums to the top, similar to how the Camera album is always first.

If possible, I'd love to be able to do it by long clicking an album and pinning it and it gets appended to the pinned albums section (such that the order is based on how I pin them)

**Comment by dnldsht** [comment] 2016-09-19 17:08
@Ketrel  I implemented this feature last day, this is a duplicate of #247 
it will be available in the next release, or if you are able build the dev branch!

**Closed as completed by dnldsht** 2016-09-19 17:08 UTC

**Comment by Ketrel** [comment] 2016-09-19 17:12
Oh wow, that's awesome.  What are the chances!

Thanks.
