### ISSUE TITLE
Images black out

### ISSUE THREAD

**Issue by submat** [UnevenSoftware/LeafPic#325] opened 2016-09-16 04:11 UTC
On Nougat. Image thumbnail takes forever to load and when done some images comes all all black and will not load. Yes, have toggled the option for media store and it made it take longer time. While I'm loving the UI and the features, wish to have this my only gallery app. Thank you.

**Comment by dnldsht** [comment] 2016-09-29 20:28
duplicate of  #317, in version 0.5.9 there is a setting called 'Subscaling Image View' that should fix this

**Closed as completed** 2016-09-29 20:29 UTC
