### ISSUE TITLE
API 20 support

### ISSUE THREAD

**Issue by pejakm** [UnevenSoftware/LeafPic#87] opened 2016-04-17 12:20 UTC
I compiled and installed on Android 4.4.4, and it crashes. Complaining something about statusbar problems.

**Comment by dnldsht** [comment] 2016-04-17 12:41
I will support kitkat very soon!

EDIT:
i started support for also api 19

**Comment by pejakm** [comment] 2016-04-20 15:03
Great, thanks! It works on my KitKat Android, but crashes when opening the image details. I can provide a log if needed.

**Comment by dnldsht** [comment] 2016-04-20 16:28
can I ask wich version of android do you have beacuse when i test the app on my HTC one(m7) with android 4.4.4 in the page viewer activity i'm not able to tap on the toolbar.

I have the image in foreground and the toolbar is behind it is caused by elevetion missing on this version but if you are able to interact with the toolbar your problem were fixed in the last commit!
@pejakm

**Comment by pejakm** [comment] 2016-04-20 16:55
4.4.4 ([MahdiRom](http://forum.xda-developers.com/optimus-4x-hd/development/rom-mahdi-rom-2-7-unofficial-beta-t2867590)).

Yes, I have that problem, too, I'm using FDroid build (v0.2.5) so I'll wait until new version. The main problem I have is that app crashes when selecting details. Here's part of exception:

```
FATAL EXCEPTION: main
Process: com.horaapps.leafpic
java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.support.v7.widget.RoundRectDrawableWithShadow
...
```

**Closed as completed** 2016-08-10 12:23 UTC
Labels: help wanted, almost done
