### ISSUE TITLE
Rotated photos?

### ISSUE THREAD

**Issue by thelostpg** [UnevenSoftware/LeafPic#340] opened 2016-09-29 16:02 UTC
Most photos are rotated, why?

This is the original image (LG's own gallery app)
http://i.imgur.com/GYzr15k.jpg
And this is the LeafPic Gallery
http://i.hizliresim.com/vZAqV6.png

**Comment by dnldsht** [comment] 2016-09-29 20:31
duplicate of #118 it is related to the exif rotation

**Closed as completed** 2016-09-29 20:31 UTC
