### ISSUE TITLE
SdCard

### ISSUE THREAD

**Issue by GrPK** [UnevenSoftware/LeafPic#520] opened 2018-02-27 19:55 UTC
Hey, I think that you already know that app is always asking for sd card write permission? Is there any way to fix it and make deleting faster? *I've read that you are working on it, but that was 6 months ago*. Thanks in advance!

**Comment by dnldsht** [comment] 2018-05-05 16:57
closing as duplicate of #478
I promise i will look into it, i just got no devices with sdcard

**Closed as completed** 2018-05-05 16:57 UTC
